standalone_tags:
  [
    {id: 350, size: 0.146},
    {id: 351, size: 0.146},
    {id: 352, size: 0.146},
    {id: 353, size: 0.146},
    {id: 354, size: 0.146},
    {id: 355, size: 0.146},
    {id: 400, size: 0.146},
    {id: 401, size: 0.146},
    {id: 402, size: 0.146},
    {id: 403, size: 0.146},
    {id: 404, size: 0.146},
    {id: 405, size: 0.146},
    {id: 406, size: 0.146},
    {id: 407, size: 0.146},
    {id: 408, size: 0.146},
    {id: 409, size: 0.146},
    {id: 410, size: 0.146},
    {id: 411, size: 0.146},
    {id: 412, size: 0.146},
    {id: 413, size: 0.146},
    {id: 414, size: 0.146},
    {id: 415, size: 0.146},
    {id: 416, size: 0.146},
    {id: 417, size: 0.146},
    {id: 418, size: 0.146},
    {id: 419, size: 0.146},
    {id: 420, size: 0.146},
  ]