# http://www.ros.org/wiki/costmap_2d

global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 0.5
  static_map: true
  rolling_window: false
  resolution: 0.05
  map_topic: /rtabmap/grid_map
  # subscribe_to_updates: true
